### ISSUE TITLE
request dependency does not install

### ISSUE THREAD

**Issue by sjclemmy** [alphagov/notifications-node-client#114]
I've just installed this package and even though it declares `request` as a dependency it does not install it. 
I notice that `request-promise` declares `request` as a peer dependency. Could it be that this overrides it? Which sounds wrong to me.
Anyway - the work around is to install `request` as a top level dependency. So perhaps this needs to be made clear in the install instructions.

**Comment by quis** [comment]
Hey @sjclemmy I think this might be because the `request` package has been deprecated. We’re looking to move away from it but aren’t Node experts so not sure what the best option is. Any suggestions?

**Comment by sjclemmy** [comment]
https://github.com/request/request/issues/3143 is a good list of alternatives. I've [axios](https://github.com/axios/axios) and [superagent](https://github.com/visionmedia/superagent) previously. Both have easy interfaces. 
I might be able to do a PR in the next week or so, if that would be helpful.

**Comment by quis** [comment]
If you could do a PR in the next week that would be amazing. I think that’s quicker than we’d be able to get to it, in the current circumstances. Both axios and superagent look well-supported so we’d be happy with either.

**Comment by CrystalPea** [comment]
@sjclemmy hey, just wanted to check up if this is something you're working on at the moment? No worries if not, just wanted to avoid duplicating work ☺️

**Comment by sjclemmy** [comment]
@CrystalPea hi there - I've not started. Looks like it was wishful thinking on my part!

**Comment by CrystalPea** [comment]
@sjclemmy no worries, hopefully I will be able to start on it soon  ☺️

**Comment by idavidmcdonald** [comment]
@sjclemmy So we've started work on this and mostly got things working with axios (work can be followed along in https://github.com/alphagov/notifications-node-client/pull/126). 

One thing we've come across is that as axios and requests have different interfaces, by changing to axios we would be changing the interface of our client and it would be a breaking change for users, we think requiring code changes for almost all users. For example `response.body` will become `response.data` and `err.error` will become `err.response.data`.

We think that this is an acceptable breaking change for users. It will require some work by them to upgrade but hopefully not too substantial.

We have also considered trying to create an abstraction of the requests and axios interface such that this isn't a breaking change and users can continue to use the old methods like `response.body`. At some point then in the future we could then remove the old methods. We think that this probably isn't worth the amount of effort on our side though.

Do you happen to have any thoughts on the above? Keen to hear from people who use the client about these potential changes

**Comment by sjclemmy** [comment]
@idavidmcdonald I think a breaking change is fine.

**Comment by idavidmcdonald** [comment]
So I've just released version 5.0.0 of the client which is now based on top of axios so I will close this issue as it is no longer relevant.

If you upgrade then please do let us know if you have any further trouble and we can help :) Thanks!
