### ISSUE TITLE
Exposure of sensitive information in follow-redirects  

### ISSUE THREAD

**Issue by Shemsedin** [alphagov/notifications-node-client#150]
Hi

There is a vulnerability in `follow-redirects`  which is `axios`dependency.  I can see that `notifications-node-client` doesn't use `axios` 0.25.0 which I believe has the fix.

Can we update the `axios` to fix this issue?

**Comment by idavidmcdonald** [comment]
Hi, I've just merged [a PR](https://github.com/alphagov/notifications-node-client/pull/151) which should bump this to 0.25.0.

It should be on npm within the next half hour. Do let me know if you come across any problems with it!

Thanks for raising :)
