### ISSUE TITLE
axios SNYK-JS-AXIOS-6671926

### ISSUE THREAD

**Issue by sfitz42** [alphagov/notifications-node-client#209]
Hello,

Would you be able to bump the axios version to resolve SNYK-JS-AXIOS-6671926 please?

I understand that the dependency version is set at `^1.7.2` but your package only seems to pull `1.7.7` rather than the latest patch version.

Thanks

**Comment by mattyod** [comment]
You possibly have something else in your package that depends upon that specific version of Axios. Or your package-lock is pinned to `1.7.7`?

**Comment by sfitz42** [comment]
Thanks - Looks like our Jenkins VM had cached 1.7.7 and wouldn't grab the new version🤦
