### ISSUE TITLE
API URL 

### ISSUE THREAD

**Issue by PhilRumens** [alphagov/notifications-node-client#5]
Is this URL correct?

https://api.notifications.service.gov.uk

I get a 404 when I try to access it.

**Comment by leohemsted** [comment]
That's the correct URL, however there is nothing at the root url to hit, hence the 404. For example, an unauth'd request to `https://api.notifications.service.gov.uk/notifications` returns a 403

**Comment by PhilRumens** [comment]
Great, thanks for the info.
