### ISSUE TITLE
Is there an example setup somewhere

### ISSUE THREAD

**Issue by colmbegs89** [alphagov/notifications-node-client#50]
Hi,

Trying to find a working example of this setup including how to setup/generate a token.

Any examples would be great we hit a 403 as we aren't sure of token setup.

**Comment by quis** [comment]
Hey @colmbegs89 have you signed up for an account at https://www.gov.uk/notify? You can generate a token (we call the them API keys) there.

**Comment by colmbegs89** [comment]
I have done that but still recieve a 403, which is why i thought there maybe an additional token and wanted to see an example js file, cheers

**Comment by colmbegs89** [comment]
I have since got it sorted out, thanks for your help

**Comment by quis** [comment]
Cool, glad to hear you got it sorted. Is there anything we could have made clearer in the docs to help you not get the error, or resolve it quicker?
