### ISSUE TITLE
`sendSms`, `sendEmail` and `sendLetter` parameters documentation doesn't match actual implementation

### ISSUE THREAD

**Issue by ollietreend** [alphagov/notifications-node-client#78]
[Documentation for the `sendEmail` method](https://docs.notifications.service.gov.uk/node.html#send-an-email) states that it accepts 5 parameters:

- `templateId` (required)
- `emailAddress` (required)
- `personalisation` (required)
- `reference` (required)
- `emailReplyToId` (optional)

However, in practice, this method actually accepts 3 parameters:

- `templateId` (required)
- `emailAddress` (required)
- `options` (optional)

`options` should be an object, and may optionally contain any of the following keys:

- `personalisation`
- `reference`
- `emailReplyToId`

The same applies to `sendSms` and `sendLetter` methods.

---

[According to the changelog](https://github.com/alphagov/notifications-node-client/blob/068c6ec65918f6c5206a32bd8b478fe1e1b8a5d1/CHANGELOG.md#400---2017-11-07), the methods were changed in 2017. But the documentation is out of date since it doesn't reflect these changes.

**Comment by quis** [comment]
Hi Ollie, as far as I can tell this issue has been fixed now. Sorry we didn’t notice and reply to your comment sooner, and thanks for writing it up so clearly.
